import org.testng.annotations.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 */

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
//        Invoker classUnderTest = new Invoker();
//        assertTrue(classUnderTest.invoke(), "someLibraryMethod should return 'true'");
    }
}
